// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBopGgbGLno38GdOu-Wo3WIzY_mbSLcCVE',
    appId: '1:419179972597:web:3a77000eae063a2a1b42bc',
    messagingSenderId: '419179972597',
    projectId: 'pvp-buganizer',
    authDomain: 'pvp-buganizer.firebaseapp.com',
    storageBucket: 'pvp-buganizer.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUEkOH15ltnGjjq4xcCe-oKEJ5l72jncI',
    appId: '1:419179972597:android:057e24fa7f2b3b3d1b42bc',
    messagingSenderId: '419179972597',
    projectId: 'pvp-buganizer',
    storageBucket: 'pvp-buganizer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-EBjgoseFmewM4wYfwIiYCxA8SksyGQE',
    appId: '1:419179972597:ios:32b0d5ead0a4354f1b42bc',
    messagingSenderId: '419179972597',
    projectId: 'pvp-buganizer',
    storageBucket: 'pvp-buganizer.appspot.com',
    iosClientId: '419179972597-f03itcpo8qodn0nm0fvcg63ugeji6j0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pvpBuganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-EBjgoseFmewM4wYfwIiYCxA8SksyGQE',
    appId: '1:419179972597:ios:402c8b0923bc87cf1b42bc',
    messagingSenderId: '419179972597',
    projectId: 'pvp-buganizer',
    storageBucket: 'pvp-buganizer.appspot.com',
    iosClientId: '419179972597-1d9keggcjdk4c7udtqgjo3k669voe6fs.apps.googleusercontent.com',
    iosBundleId: 'com.example.pvpBuganizer.RunnerTests',
  );
}
